package com.fmlfpl.fplUpdates.mappings;

public class EventHistory {

    String event;
    int points;
    int total_points;
    int rank;
    int rank_sort;
    int overall_rank;
    int bank;
    int value;
    int event_transfers;
    int event_transfers_cost;
    int points_on_bench;

    //custom field, added from the meta info
    String active_chip;

    //AUTOGENERATED GETTERS AND SETTERS
    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public int getPoints() {
        return points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public int getTotal_points() {
        return total_points;
    }

    public void setTotal_points(int total_points) {
        this.total_points = total_points;
    }

    public int getRank() {
        return rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    public int getRank_sort() {
        return rank_sort;
    }

    public void setRank_sort(int rank_sort) {
        this.rank_sort = rank_sort;
    }

    public int getOverall_rank() {
        return overall_rank;
    }

    public void setOverall_rank(int overall_rank) {
        this.overall_rank = overall_rank;
    }

    public int getBank() {
        return bank;
    }

    public void setBank(int bank) {
        this.bank = bank;
    }

    public int getValue(){
        return value;
    }

    public void setValue(int value){
        this.value = value;
    }

    public int getEvent_transfers() {
        return event_transfers;
    }

    public void setEvent_transfers(int event_transfers) {
        this.event_transfers = event_transfers;
    }

    public int getEvent_transfers_cost() {
        return event_transfers_cost;
    }

    public void setEvent_transfers_cost(int event_transfers_cost) {
        this.event_transfers_cost = event_transfers_cost;
    }

    public int getPoints_on_bench() {
        return points_on_bench;
    }

    public void setPoints_on_bench(int points_on_bench) {
        this.points_on_bench = points_on_bench;
    }

    public String getActive_chip() {
        return active_chip;
    }

    public void setActive_chip(String active_chip) {
        if(active_chip.equals("ull,")){
            this.active_chip = null;
        }else {
            this.active_chip = active_chip;
        }
    }
}
